- 👋 Hi, I’m @Mirguee
- 👀 I’m interested in making games but i'm too lazy for making one.
- 🌱 I’m currently learning how to use Gamemaker
- 📫 How to reach me [https://twitter.com/Mirguee_](https://twitter.com/Mirguee_)
- 😄 Pronouns: He/Him
